name: BuildForUnity

# Attention
# iOS use static
# Android use dynamic
# Windows use dynamic
# MacOs use dynamic

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - release/*
  pull_request:
    branches:
    - main
    - release/*

concurrency:
  # Cancel any workflow currently in progress for the same PR.
  # Allow running concurrently with any other commits.
  group: build-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions: read-all

jobs:
  build-windows:
    name: WinUser
    needs: []
    strategy:
      fail-fast: false
      matrix:
        config: ['Release']
        plat: [windows] # TODO: Support gamecore_console
        os: ['windows-2022']
        arch: [x64]
        tls: [quictls]
        static: ['']
        exclude:
        # OpenSSL/quictls doesn't support arm64
        - tls: quictls
          arch: arm64
        # TODO: FIX: OpenSSL/quictls build fails with UWP
        - plat: uwp
          tls: quictls
        # TODO: FIX: Static builds fail with UWP
        - plat: uwp
          static: '-Static'
    uses: ./.github/workflows/build-reuse-win.yml
    with:
      config: ${{ matrix.config }}
      plat: ${{ matrix.plat }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      static: ${{ matrix.static }}
      repo: ${{ github.repository }}

  build-ubuntu:
    name: Ubuntu
    needs: []
    strategy:
      fail-fast: false
      matrix:
        config: ['Release']
        plat: [android]
        os: ['ubuntu-24.04']
        arch: [arm64]
        tls: [quictls]
        systemcrypto: ['', '-UseSystemOpenSSLCrypto']
        static: ['']
        clang: ['', '-Clang']
        codecheck: ['', '-CodeCheck']
        xdp: ['', '-UseXdp']
        exclude:
        # Android doesn't support x86, XDP, Clang, CodeCheck or SystemCrypto
        - plat: android
          arch: x86
        - plat: android
          systemcrypto: '-UseSystemOpenSSLCrypto'
        - plat: android
          xdp: "-UseXdp"
        - plat: android
          clang: '-Clang'
        - plat: android
          codecheck: '-CodeCheck'
        # CodeCheck doesn't work with SystemCrypto, Clang, Static or Release builds
        - codecheck: '-CodeCheck'
          systemcrypto: '-UseSystemOpenSSLCrypto'
        - codecheck: '-CodeCheck'
          clang: '-Clang'
        - codecheck: '-CodeCheck'
          static: '-Static'
        - codecheck: '-CodeCheck'
          config: Release
        # Static build can't dynamically link to libcrypto
        - static: '-Static'
          systemcrypto: '-UseSystemOpenSSLCrypto'
        # No openssl system crypto on ubuntu 22.04 or 24.04
        - os: 'ubuntu-22.04'
          systemcrypto: '-UseSystemOpenSSLCrypto'
        - os: 'ubuntu-24.04'
          systemcrypto: '-UseSystemOpenSSLCrypto'
        # Linux xdp is for x64 ubuntu24.04 only for now
        - xdp: "-UseXdp"
          os: 'ubuntu-22.04'
        - xdp: "-UseXdp"
          arch: x86
    uses: ./.github/workflows/build-reuse-unix.yml
    with:
      config: ${{ matrix.config }}
      plat: ${{ matrix.plat }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      systemcrypto: ${{ matrix.systemcrypto }}
      static: ${{ matrix.static }}
      clang: ${{ matrix.clang }}
      codecheck: ${{ matrix.codecheck }}
      xdp: ${{ matrix.xdp }}
      repo: ${{ github.repository }}

  build-darwin:
    name: MacOs
    needs: []
    strategy:
      fail-fast: false
      matrix:
        config: ['Release']
        plat: [macos, ios]
        os: ['macos-13']
        arch: [arm64]
        tls: [quictls]
        #static: ['', '-Static']
    uses: ./.github/workflows/build-reuse-unix.yml
    with:
      config: ${{ matrix.config }}
      plat: ${{ matrix.plat }}
      os: ${{ matrix.os }}
      arch: ${{ matrix.arch }}
      tls: ${{ matrix.tls }}
      static: ${{ matrix.plat == 'ios' && '-Static' || '' }}
      repo: ${{ github.repository }}
